language: node_js
node_js:
  - "6.10"

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
    - npm install

after_script:
- cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
