version: '3'
services:
  web:
    build: ./nginx/
    ports: 
      - "80:80"
    volumes:
      - /www/public
  renderer:
    build: ./renderer/
    ports:
      - "300480:3000"
      
    command: nodemon -L app/bin/www